### ISSUE TITLE
license information

### ISSUE THREAD

**Issue by sharif26** [johnlonganecker/libpostal-rest#3]
Hi
We use this repo which is very helpful.
But there is one issue: it does not have any license information.
Could you please update the repo with necessary license information.
Thanks in advance

**Comment by johnlonganecker** [comment]
Yeah of course, I am totally open to that. Do you have a particular LICENSE that works best for you?

**Comment by kpcyrd** [comment]
MIT is a good and simple choice. :)

Ultimately any license works that's listed on https://wiki.debian.org/DFSGLicenses, although some of them are slightly esoteric.

**Comment by johnlonganecker** [comment]
Sounds good I will add a MIT License!
