### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by kpcyrd** [johnlonganecker/libpostal-rest#4]
hello!

I've been looking at the libpostal package in alpine and noticed libpostal-rest is missing. I'd like to add it to alpine too, but there's currently no tagged release.

Any chance you could create a tag that I could use as a release after #3 is solved?

Thanks!

**Comment by johnlonganecker** [comment]
I finally got around to tagging and creating a GH release! not sure if you are still interested in that or not. Sorry for the long delay.
